#!/bin/bash

local BUILD_BRANCH='master'
local BUILD_COMMAND='npm run publish'
local BUILD_PATH='dist index.html feed'
local BUILD_COMMIT_TITLE='publish'

local CURRENT_BRANCH=$(git branch | grep --color=never '^\* ' | cut -d' ' -f 2)

local ADD_BUILD_COMMAND="git add -f ${BUILD_PATH}"

# Switch to the build branch
git branch -D ${BUILD_BRANCH}
git checkout -b ${BUILD_BRANCH}

# Build, commit, push
eval ${BUILD_COMMAND}
eval ${ADD_BUILD_COMMAND}
git commit -m ${BUILD_COMMIT_TITLE}
git push -f origin ${BUILD_BRANCH}

# Switch back and clean up
git checkout ${CURRENT_BRANCH}
git branch -D ${BUILD_BRANCH}
eval ${BUILD_COMMAND}
